### ISSUE TITLE
all settings checkboxes should be checked when extension is newly installed

### ISSUE THREAD

**Issue by ganganimaulik** [ganganimaulik/social-feed-blocker#10]
<img width="468" alt="Screenshot 2023-07-04 at 11 50 58 PM" src="https://github.com/ganganimaulik/social-feed-blocker/assets/10296400/244b3f33-07e4-43e9-87fe-336b98be163e">

when new user installs extension we need to check all options by default 

we can introduce one boolean parameter to initConfig function - onInstalled (default false) = if set to true we force selected attribute in config to be true otherwise keep existing logic as is.

and while calling initConfig on line 7 of background.js we set onInstalled argument as true.

**Comment by aryanas159** [comment]
Is this issue fixed?

**Comment by ganganimaulik** [comment]
> Is this issue fixed?



> Is this issue fixed?

Hi, I missunderstood issue before...  

issue is when we unselect all checkboxes (by clicking on facebook, twitter, ig, reddit, youtube, linkedin) then uninstall extension and then reinstall back.. I think it happens because chrome doesn't delete local storage of extension when uninstalling
